### ISSUE TITLE
Status Page 需求

### ISSUE THREAD

**Issue by bestony** [LCTT/LCTT.github.io#2]
负责人：@vizv 
数据提供： @lujun9972 

Status Page 基本设想：
能够完整的展现仓库的一些基本情况，并辅助展示翻译进度，起到引导作用。

具体功能点

1. [x] 文章申领情况列表
2. [x] 文章天梯榜列表
4. [x] 未认领文章列表。
3. [x] 导航页面。

## 数据示例
```
{
  
    "translating": [
        {
            "file": "xxxx.md",
            "time": "2018-02-02",
            "user": "bestony"
        },
       ...
    ],
    "unselect": [
        {
            "file": "xxx.md",
            "time": "2018-02-02"
        },
        ...
    ]
}
```

## 补充说明

- difficulty 为天梯榜列表
- translating 为翻译中文章
- unselect 为未认领文章

- 数据通过 CI 生成，置放在：https://lctt.github.io/translateproject/ 路径下，前端页面请求获取。
- 前端页面放置在本仓库中，从而使得可以通过lctt.github.io进行访问。

- time 均为上一次 commit 时间。如果后续加入 meta-data ，可以读取 metadata

## 简单原型

![](https://postimg.aliavv.com/newmbp/heppb.jpg)

**Comment by lujun9972** [comment]
天梯榜列表是个什么概念？
另外这个json似乎不太好搞，shell似乎只能用jq来组合json，我需要学习一下，可能不会那么快搞定
@bestony

**Comment by bestony** [comment]
天梯榜是长期没有人翻译的文章，暂时仅以时间来判断是否进入天梯榜，比如，45 天以上没有被人认领的文章。

其次，关于数据格式，这个你和 @vizv 沟通一下，看看你们两个人怎么协作最方便。他来负责前端的界面和交互。

**Comment by lujun9972** [comment]
用JSON格式交互没问题，只是我需要一些时间来搞，实在不行我就用python来做算了

**Comment by bestony** [comment]
这部分你决定就OK。应该不急，而且 Vizv 应该也不会太快做完。不过你需要确定下上面的格式是否可以生成？如果可以生成，那他可以先用 Fake data 来做，等上线了再切换 URL 就好了。

**Comment by bestony** [comment]
@wxy 老王，你看一下界面的原型，看看有没有什么其他的元素需要加上去的。

**Comment by bestony** [comment]
## NavBar 链接

- Home: https://linux.cn/lctt/
- Wiki :  https://lctt.github.io/wiki
- Token: https://lctt.linux.cn/
- Shop: https://shop.linux.cn/

**Comment by bestony** [comment]
前端数据展示限制

1. Tab 内各 List 仅显示 300 条，多出来的暂时不显示。

数据生成方面不限制，全量生成。

**Comment by lujun9972** [comment]
格式可以做到

**Comment by wxy** [comment]
我补充几点：

- json 文件中如果只有 `filename`，虽然文件名也具有一定的说明性，但是似乎不如提取文内标题？（如果额外处理工作量大的话，我觉得算了）
- “翻译中”作为默认选项卡，可以督促进度之用。此处显示条目的样式为两列表格：
    - 译者，限定宽度，太长的名字后面部分隐藏
    - 文件名，并在背景以已经翻译的天数为进度条（以 30 天为满周期，即 30 个格子）
- “天梯榜”为第二选项卡，条目列表为两列表格：
   - 天数
   - 文件名
- “待认领”似乎列出最新增加的文章就可以
- 呈现路径应该是： https://lctt.github.io/TranslateProject/ （有大小写区别吧）

**Comment by lujun9972** [comment]
天梯榜似乎只是待认领中挑选时间超过一定期限的数据，那生成json时有必要生成两份数据吗？直接在前端从unselect里面挑选行不行？

**Comment by bestony** [comment]
有道理，你这边做好，Vizv那边前端筛选就好。

**Comment by bestony** [comment]
呈现路径应该是lctt.github.io，如果挂在translateproject 下,可能干扰主库。

**Comment by bestony** [comment]
之所以干扰主库，因为 travis 对 deploy 好像是 force upload，不保留历史文件，这就导致需要把代码写在主库里。

**Comment by lujun9972** [comment]
为啥要保留历史文件？
这是要把script写到lctt.github.io里面？

**Comment by bestony** [comment]
如果按老王所说，在translateproject二级目录展示，就需要保存历史文件里。我倾向于将status pages 挂在当前这个目录，主库的gh-pages 提供数据。

**Comment by lujun9972** [comment]
我把script放到TranslateProject仓库里，在lctt.github.io的CI里clone TranslateProject后直接调用里面的脚本，生成的数据重定向到lctt.github.io的status.json文件中，这样可行？

**Comment by lujun9972** [comment]
脚本写出来了，在我电脑上跑一次要近40秒...
```
[lujun9972@T430S TranslateProject]$ time ./scripts/status.sh  >/tmp/status.json

real	0m37.797s
user	0m33.286s
sys	0m5.738s
```

**Comment by bestony** [comment]
每日运行一次，还行。

数据放置的话，你最好测试一下 travis 的 deploy 是否会清空数据，我印象中会被清空。

**Comment by lujun9972** [comment]
清空数据是什么意思？
status page不是只需要展示现有的状态就行了吗？还需要历史数据干啥？

**Comment by bestony** [comment]
travis 的 deploy 会把分支清空掉，再重新加入文件。如果是这样的话，deploy代码里就需要加入 html 文件了。

**Comment by lujun9972** [comment]
这次不是采用TranslateProject badge那种模式吗？
CI里只是负责把生成的json推倒一个branch中存着，然后主库代码不变，只需要前端从分支里读json就好了？

**Comment by bestony** [comment]
没错，问题就在于，如果按照老王的意思，挂在 translateproject 项目的页面中，会导致vizv 的代码和你的代码放在一处管理，污染主库。
对于你来说，基本没区别，你只要确保生成json即可，只是Vizv那边的前端页面放在哪的问题。

**Comment by bestony** [comment]
如果挂在 lctt.github.io 下，你按照badge的模式，生成json即可，vizv在这个仓库维护前端就好啦。这也就是为啥我在这里开issue的原因。

如果挂在二级目录，需要在主库的master里加入 html、css、js，我觉得污染了主库文件。

**Comment by bestony** [comment]
@wxy 
> “待认领”似乎列出最新增加的文章就可以

此处应该是列举所有不在天体榜上且未被认领的内容吧。

> 呈现路径应该是： https://lctt.github.io/TranslateProject/ （有大小写区别吧）

此处可能会导致主库的 master 内需要加入 HTML、CSS 、JS 文件。建议放在 LCTT.github.io 上。

**Comment by bestony** [comment]
@vizv @lujun9972  

关于文件、数据

TranslateProject 仓库每日跟随 Crontab  生成 JSON 。生成完成后，提供一个 URL 粘贴在 ISSUE 内

Vizv 的前端脚本放置在本仓库的 `gh-pages` 分支下。

二者分开，避免对主库的污染。

**Comment by bestony** [comment]
1. Item List 需要使用 Ordered List
2. 天数显示 ：XXXX天前

**Comment by bestony** [comment]
@vizv 

需求：
- [ ] **CI 自动构建**：实现通过CI自动构建，自动发布。提交 PR 到 lc-status 仓库，merge 后，自动发布到本仓库。

**Comment by bestony** [comment]
PC 端需要更新：

待认领及天梯榜：

1. 每行三列，分别为**时间**、**文件名**、**认领按钮**
2. 天梯榜时间格式：`YYYY/MM/DD` ，待认领时间格式：`MM - DD` 
3. 文件名需要过滤前面的日期及最后的 `.md`
4. 文件名加跳转原文链接,`target=_blank`

翻译中：

1. 每行四列，分别为**For循环的 Index**、**日期**、**文件名**、**认领按钮**
2. 时间格式：XXX天以前
3. 文件名需要过滤前面的日期及最后的 `.md`
4. 文件名加跳转原文链接,`target=_blank`

文件名跳转链接格式：`https://github.com/LCTT/TranslateProject/blob/master/` + 文件路径

**Comment by vizv** [comment]
文件名过滤已完成

**Comment by vizv** [comment]
点击文件名（标题）打开新预览页面完成，认领按钮也会打开新页面

**Comment by bestony** [comment]
移动端展示

移动端受限于设备的能力，以浏览为主，因此，移除认领按钮。

**待认领及天梯榜**

mockup：

![](https://ws1.sinaimg.cn/large/006tNbRwly1fxlg8e8p9wj30oc05qwej.jpg)

内容分为两行，第一行为文件名，第二行为选题时间

1. 文件名删除前面的日期及后面的`.md`
2. 选题时间应略小于文件名，以突出文件名。
3. 文件名点击后可以跳转到内容的浏览页面。
4. 文件名加跳转原文链接,`target=_blank`

**翻译中**

![image](https://user-images.githubusercontent.com/13283837/48998276-fc471600-f18d-11e8-985e-4be10dddab6f.png)

内容分为两行，第一行为文件名，第二行为认领时间和认领人

1. 文件名删除前面的日期及后面的`.md`
2. 认领人左对齐；认领时间右对齐
2. 认领时间和认领人应略小于文件名，以突出文件名。
3. 文件名点击后可以跳转到内容的浏览页面。
4. 文件名加跳转原文链接,`target=_blank`

文件名跳转链接格式：https://github.com/LCTT/TranslateProject/blob/master/ + 文件路径

**Comment by vizv** [comment]
PC 端的 polish 已完成

**Comment by lujun9972** [comment]
天梯榜比待选还多，是不是不太合理啊。考虑按百分比设置天梯榜？比如前20%的纳入天梯榜，剩下的纳入待选

**Comment by bestony** [comment]
@vizv

更新需求

1. 天梯榜筛选规则为按时间长短逆序排列前 20% 的文章，列入天梯榜。

**Comment by vizv** [comment]
@lujun9972 等待 @wxy 和 @bestony 的确认

**Comment by vizv** [comment]
@bestony 了解，马上做

**Comment by vizv** [comment]
@lujun9972 @bestony 已部署

**Comment by vizv** [comment]
基本上应该没什么了吧，你们验收下然后把这个 issue 关了。以后每个新 feature 开新的 issue 好了。
